// Changing Course name
const course = {
  programming_foundation: {
    monday: [
      "RD412<br/><small>Practical</small>",
      "RD412<br/><small>Practical</small>",
      "ENA412<br /><small>Theory</small>",
      "Group Study",
      "Group Study",
      "CW412<br /><small>Practical</small>",
      "CW412<br /><small>Practical</small>",
      "CW412<br /><small>Practical</small>",
    ],
    tuesday: [
      "RD412<br /><small>Practical</small>",
      "RD412<br /><small>Practical</small>",
      "RD412<br /><small>Practical</small>",
      "Research",
      "",
      "ENA412<br /><small>Practical</small>",
      "ENA412<br /><small>Practical</small>",
      "ENA412<br /><small>Practical</small>",
    ],
    wednesday: [
      "ENA412<br /><small>Theory</small>",
      "ENA412<br /><small>Theory</small>",
      "ENA412<br /><small>Theory</small>",
      "ENA412<br /><small>Theory</small>",
      "",
      "ENA412<br /><small>Practical</small>",
      "ENA412<br /><small>Practical</small>",
      "ENA412<br /><small>Practical</small>",
    ],
    thursday: [
      "ENA412<br /><small>Theory</small>",
      "ENA412<br /><small>Practical</small>",
      "ENA412<br /><small>Practical</small>",
      "Research",
      "",
      "FDM<br /><small>Theory</small>",
      "FDM<br /><small>Theory</small>",
      "FDM<br /><small>Theory</small>",
    ],
    friday: [
      "Group Study",
      "CF412<br /><small>Theory</small>",
      "CF412<br /><small>Practical</small>",
      "CF412<br /><small>Practical</small>",
      "",
      "",
      "",
      "",
    ],
  },
  project_management: {
    monday: [
      "PMG511",
      "PMG511",
      "PMG511",
      "",
      "PCM611",
      "PCM611",
      "PCM611",
    ],
    tuesday: [
      "",
      "",
      "",
      "",
      "MAC611",
      "MAC611",
      "MAC611",
    ],
    wednesday: [
      "BMG511",
      "BMG611",
      "BMG611",
      "",
      "IPM511",
      "IPM511",
      "IPM511",
    ],
    thursday: [
      "",
      "",
      "",
      "",
      "FPM511",
      "FPM511",
      "FPM511",
    ],
    friday: [
      "",
      "",
      "",
      "SUPPORT",
      "SUPPORT",
      "",
      "",
    ],
  },
  cyber_security: {
    monday: [
      "ADI632<br/><small>Practical</small>",
      "ADI632<br/><small>Practical</small>",
      "ADI632<br /><small>Theory</small>",
      "ADI632<br/><small>Practical</small>",
      "",
      "ADI632<br/><small>Practical</small>",
      "Group Study",
      "",
    ],
    tuesday: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    wednesday: [
      "AD632<br /><small>Practical</small>",
      "AD632<br /><small>Practical</small>",
      "AD632<br /><small>Practical</small>",
      "AD632<br /><small>Practical</small>",
      "",
      "AD632<br /><small>Practical</small>",
      "Group Study",
      "",
    ],
    thursday: [
      "AD632<br /><small>Practical</small>",
      "AD632<br /><small>Practical</small>",
      "AD632<br /><small>Practical</small>",
      "AD632<br /><small>Practical</small>",
      "",
      "AD632<br /><small>Practical</small>",
      "Group Study",
      "",
    ],
    friday: [
      "CSP632<br /><small>Theory</small>",
      "CSP632<br /><small>Theory</small>",
      "CSP632<br /><small>Practical</small>",
      "CSP632<br /><small>Practical</small>",
      "",
      "CSP632<br /><small>Practical</small>",
      "Research",
      "",
    ],
  },
  IT_technical_support: {
    monday: [
      "PS412<br /><small>Theory</small>",
      "PS412<br /><small>Theory</small>",
      "PS412<br /><small>Practical</small>",
      "Group study<br /><small>ML1</small>",
      "PS412<br /><small>Practical</small>",
      "PS412<br /><small>Theory</small>",
      "PS412<br /><small>Theory</small>",
      "Research",
    ],
    tuesday: [
      "FOCUS ON",
      "INTERNATIONAL",
      "PREPARATIONS<br />MD-102",
      "",
      "IBP412<br /><small>Practical</small>",
      "IBP412<br /><small>Practical</small>",
      "IBP412<br /><small>Practical</small>",
      "",
    ],
    wednesday: [
      "Group study<br /><small>ML1</small>",
      "IBP412<br /><small>Practical</small>",
      "IBP412<br /><small>Practical</small>",
      "IBP412<br /><small>Practical</small>",
      "Group study<br /><small>ML1</small>",
      "MDA412<br /><small>Theory</small>",
      "MDA412<br /><small>Theory</small>",
      "MDA412<br /><small>Practical</small>",
    ],
    thursday: [
      "MDA412<br /><small>Theory</small>",
      "MDA412<br /><small>Theory</small>",
      "MDA412<br /><small>Practical</small>",
      "Group study<br /><small>ML1</small>",
      "",
      "FDM411<br /><small>Theory</small>",
      "FDM411<br /><small>Theory</small>",
      "FDM411<br /><small>Theory</small>",
    ],
    friday: [
      "Group Study",
      "Lab Session",
      "Lab Session",
      "Lab Session",
      "",
      "Research",
      "Research",
      "Research",
    ],
  },
};
